<?php

namespace Database\Seeders;

use App\Models\Hospital;
use Illuminate\Database\Seeder;

class HospitalSeeder extends Seeder
{
    public function run(): void
    {
        $hospitals = [
            [
                'name' => 'Bệnh viện Chợ Rẫy',
                'code' => 'CR-79',
                'province_code' => '79',
                'ward_code' => '27301',
                'address' => '201B Nguyễn Chí Thanh, TP. Hồ Chí Minh',
                'latitude' => 10.7565,
                'longitude' => 106.6594,
                'contact_phone' => '02838554137',
                'contact_email' => 'sos@choray.vn',
            ],
            [
                'name' => 'Bệnh viện Truyền máu Huyết học TP.HCM',
                'code' => 'TMHH-79',
                'province_code' => '79',
                'ward_code' => '27238',
                'address' => '118 Hồng Bàng, TP. Hồ Chí Minh',
                'latitude' => 10.7552,
                'longitude' => 106.6656,
                'contact_phone' => '02839557858',
                'contact_email' => 'dieuphoi@bthh.org.vn',
            ],
            [
                'name' => 'Bệnh viện Bạch Mai',
                'code' => 'BM-01',
                'province_code' => '01',
                'ward_code' => '00292',
                'address' => '78 Giải Phóng, Hà Nội',
                'latitude' => 21.0008,
                'longitude' => 105.8413,
                'contact_phone' => '02438693731',
                'contact_email' => 'sos@bachmai.vn',
            ],
            [
                'name' => 'Bệnh viện Hữu nghị Việt Đức',
                'code' => 'VD-01',
                'province_code' => '01',
                'ward_code' => '00082',
                'address' => '40 Tràng Thi, Hà Nội',
                'latitude' => 21.0283,
                'longitude' => 105.8466,
                'contact_phone' => '02438253531',
                'contact_email' => 'sos@vietduchospital.edu.vn',
            ],
            [
                'name' => 'Bệnh viện Trung ương Quân đội 108',
                'code' => 'QD108-01',
                'province_code' => '01',
                'ward_code' => '00070',
                'address' => '1 Trần Hưng Đạo, Hà Nội',
                'latitude' => 21.0184,
                'longitude' => 105.8613,
                'contact_phone' => '02462784116',
                'contact_email' => 'sos@benhvien108.vn',
            ],
            [
                'name' => 'Bệnh viện Trung ương Huế',
                'code' => 'TWH-46',
                'province_code' => '46',
                'ward_code' => '19753',
                'address' => '16 Lê Lợi, Huế',
                'latitude' => 16.4628,
                'longitude' => 107.5908,
                'contact_phone' => '02343822325',
                'contact_email' => 'sos@bvtwhue.vn',
            ],
            [
                'name' => 'Bệnh viện Đà Nẵng',
                'code' => 'DN-48',
                'province_code' => '48',
                'ward_code' => '20275',
                'address' => '124 Hải Phòng, Đà Nẵng',
                'latitude' => 16.0718,
                'longitude' => 108.2140,
                'contact_phone' => '02363821218',
                'contact_email' => 'sos@dananghospital.vn',
            ],
            [
                'name' => 'Bệnh viện Đại học Y Dược TP.HCM',
                'code' => 'UMC-79',
                'province_code' => '79',
                'ward_code' => '27238',
                'address' => '215 Hồng Bàng, TP. Hồ Chí Minh',
                'latitude' => 10.7559,
                'longitude' => 106.6628,
                'contact_phone' => '02838554269',
                'contact_email' => 'sos@umc.edu.vn',
            ],
            [
                'name' => 'Bệnh viện Nhi Đồng 1',
                'code' => 'ND1-79',
                'province_code' => '79',
                'ward_code' => '27226',
                'address' => '341 Sư Vạn Hạnh, TP. Hồ Chí Minh',
                'latitude' => 10.7683,
                'longitude' => 106.6693,
                'contact_phone' => '02839271119',
                'contact_email' => 'sos@nhidong.org.vn',
            ],
            [
                'name' => 'Bệnh viện Thống Nhất',
                'code' => 'TN-79',
                'province_code' => '79',
                'ward_code' => '27232',
                'address' => '1 Lý Thường Kiệt, TP. Hồ Chí Minh',
                'latitude' => 10.7852,
                'longitude' => 106.6539,
                'contact_phone' => '02838690277',
                'contact_email' => 'sos@bvtn.org.vn',
            ],
            [
                'name' => 'Bệnh viện Đa khoa tỉnh Thanh Hóa',
                'code' => 'DKTH-38',
                'province_code' => '38',
                'ward_code' => '14797',
                'address' => '181 Hải Thượng Lãn Ông, phường Hạc Thành, Thanh Hóa',
                'latitude' => 19.7990,
                'longitude' => 105.7768,
                'contact_phone' => '19001536',
                'contact_email' => 'sos@bvdktinhthanhhoa.com.vn',
            ],
            [
                'name' => 'Bệnh viện Nhi Thanh Hóa',
                'code' => 'NHI-38',
                'province_code' => '38',
                'ward_code' => '14797',
                'address' => '724 Quang Trung, phường Hạc Thành, Thanh Hóa',
                'latitude' => 19.7844,
                'longitude' => 105.7808,
                'contact_phone' => '02373953979',
                'contact_email' => 'bvnhith.tph@gmail.com',
            ],
            [
                'name' => 'Bệnh viện Hữu nghị Việt Tiệp',
                'code' => 'VT-31',
                'province_code' => '31',
                'ward_code' => '11383',
                'address' => '1 Nhà Thương, phường Lê Chân, Hải Phòng',
                'latitude' => 20.8524,
                'longitude' => 106.6818,
                'contact_phone' => '1900232361',
                'contact_email' => 'sos@viettiephospital.vn',
            ],
            [
                'name' => 'Bệnh viện Phụ sản Hải Phòng',
                'code' => 'PSHP-31',
                'province_code' => '31',
                'ward_code' => '11311',
                'address' => '19 Trần Quang Khải, phường Hồng Bàng, Hải Phòng',
                'latitude' => 20.8588,
                'longitude' => 106.6830,
                'contact_phone' => '02257104999',
                'contact_email' => 'benhvienphusan1978hp@gmail.com',
            ],
            [
                'name' => 'Bệnh viện Trung ương Thái Nguyên',
                'code' => 'TW-TN-19',
                'province_code' => '19',
                'ward_code' => '05443',
                'address' => '479 Lương Ngọc Quyến, phường Phan Đình Phùng, Thái Nguyên',
                'latitude' => 21.5881,
                'longitude' => 105.8309,
                'contact_phone' => '02083855125',
                'contact_email' => 'vanthu@bvdktuthainguyen.gov.vn',
            ],
            [
                'name' => 'Bệnh viện A Thái Nguyên',
                'code' => 'BVA-TN-19',
                'province_code' => '19',
                'ward_code' => '05455',
                'address' => 'Đường Quang Trung, phường Quyết Thắng, Thái Nguyên',
                'latitude' => 21.5868,
                'longitude' => 105.8217,
                'contact_phone' => '02083846112',
                'contact_email' => 'hotro@benhviena.vn',
            ],
            [
                'name' => 'Bệnh viện Đa khoa Trung ương Cần Thơ',
                'code' => 'CT-92',
                'province_code' => '92',
                'ward_code' => '31135',
                'address' => '315 Nguyễn Văn Linh, Cần Thơ',
                'latitude' => 10.0306,
                'longitude' => 105.7683,
                'contact_phone' => '02923732920',
                'contact_email' => 'sos@bvtwct.vn',
            ],
        ];

        foreach ($hospitals as $hospital) {
            Hospital::query()->updateOrCreate(
                ['code' => $hospital['code']],
                [...$hospital, 'is_active' => true],
            );
        }
    }
}
